version: "3.8"
# remember:
# container has its own localhost with its own ip address
# be sure you can access mysql shell INSIDE the container if getting connection issues
services:
  reviews_endpoint:
    command: sh -c "echo hello world && sleep 5 && npm start"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - reviews_database

  reviews_database:
    image: mysql:8.0
    platform: linux/amd64
    ports:
        - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    command: --default-authentication-plugin=mysql_native_password
